' Developer Express Code Central Example:
' An example of custom Drag and Drop
' 
' This example demonstrates how to customize Drag and Drop feature for the
' TreeList using Drag and Drop-related events.
' Values of the "Position" and
' "Department" fields change depending on the new location of a record.
' 
' You can find sample updates and versions for different programming languages here:
' http://www.devexpress.com/example=E3921
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Namespace WPF_GridControl_Custom_Drag_and_Drop.Properties

    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")>
    Friend NotInheritable Partial Class Settings
        Inherits Global.System.Configuration.ApplicationSettingsBase

        Private Shared defaultInstance As WPF_GridControl_Custom_Drag_and_Drop.Properties.Settings = CType((Global.System.Configuration.ApplicationSettingsBase.Synchronized(New WPF_GridControl_Custom_Drag_and_Drop.Properties.Settings())), WPF_GridControl_Custom_Drag_and_Drop.Properties.Settings)

        Public Shared ReadOnly Property [Default] As Settings
            Get
                Return WPF_GridControl_Custom_Drag_and_Drop.Properties.Settings.defaultInstance
            End Get
        End Property
    End Class
End Namespace
